annotation_tuples = [
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 22, 51,
     "http://www.wikidata.org/entity/Q2707406", "ASSEMBLEA REGIONALE SICILIANA"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 146, 162,
     "http://www.wikidata.org/entity/Q686822", "DISEGNO DI LEGGE"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 217, 223,
     "http://www.wikidata.org/entity/Q112151", "Turano"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 376, 392,
     "http://www.wikidata.org/entity/Q686822", "DISEGNO DI LEGGE"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 496, 507,
     "http://www.wikidata.org/entity/Q11451", "agricoltura"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 509, 518,
     "http://www.wikidata.org/entity/Q8148", "industria"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 831, 841,
     "http://www.wikidata.org/entity/Q16530425", "Cancelleri"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 1225, 1241,
     "http://www.wikidata.org/entity/Q686822", "disegno di legge"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 1299, 1307,
     "http://www.wikidata.org/entity/Q3705013", "delibera"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 1589, 1607,
     "http://www.wikidata.org/entity/Q1460", "Regione  siciliana"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 1646, 1666,
     "http://www.wikidata.org/entity/Q32766", "Corte costituzionale"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 2156, 2186,
     "http://www.wikidata.org/entity/Q1221208", "contratto  a tempo determinato"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/385", 2539, 2556,
     "http://www.wikidata.org/entity/Q1460", "Regione siciliana"),
    ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/102", 47, 84,
     "http://www.wikidata.org/entity/Q686822", """PROPOSTA
                         DI LEGGE"""),
     ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/102", 204, 214,
      "http://www.wikidata.org/entity/Q37813", "ecosistemi"),
     ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/102", 470, 480,
      "http://www.wikidata.org/entity/Q957076", "mondo  non"),
     ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/102", 656, 659,
      "http://www.wikidata.org/entity/Q40970", "ciò"),
     ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/102", 679, 691,
      "http://www.wikidata.org/entity/Q162719", "neoliberista"),
     ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/102", 868, 878,
      "http://www.wikidata.org/entity/Q37813", "ecosistema"),
     ("http://dati.openars.org/legislatura/xvi/attivita-parlamentare/ddl/102", 881, 884,
      "http://www.wikidata.org/entity/Q40970", "Ciò"),

     ]

